export const DEFAULT_CHAT_STYLE = {
  presetId: 'wechat-green',
  background: '#ededed',
  ownerTextColor: '#111111',
  ownerBgColor: '#95EC69',
  otherTextColor: '#111111',
  otherBgColor: '#ffffff',
  dateTextColor: '#999999',
  avatarRadius: 4,
  bubbleRadius: 4,
}

export const CHAT_STYLE_PRESETS = [
  {
    id: 'wechat-green',
    label: '微信绿',
    thumb: { owner: '#95EC69', other: '#ffffff', bg: '#ededed' },
    style: { ...DEFAULT_CHAT_STYLE, presetId: 'wechat-green' },
  },
  {
    id: 'wechat-blue',
    label: '经典蓝',
    thumb: { owner: '#1261FF', other: '#ffffff', bg: '#ededed' },
    style: {
      presetId: 'wechat-blue',
      background: '#ededed',
      ownerTextColor: '#ffffff',
      ownerBgColor: '#1261FF',
      otherTextColor: '#111111',
      otherBgColor: '#ffffff',
      dateTextColor: '#999999',
      avatarRadius: 4,
      bubbleRadius: 4,
    },
  },
  {
    id: 'wechat-teal',
    label: '青绿',
    thumb: { owner: '#07C160', other: '#ffffff', bg: '#ededed' },
    style: {
      presetId: 'wechat-teal',
      background: '#ededed',
      ownerTextColor: '#ffffff',
      ownerBgColor: '#07C160',
      otherTextColor: '#111111',
      otherBgColor: '#ffffff',
      dateTextColor: '#999999',
      avatarRadius: 4,
      bubbleRadius: 4,
    },
  },
  {
    id: 'warm-orange',
    label: '暖橙',
    thumb: { owner: '#FF8C42', other: '#ffffff', bg: '#f5f0eb' },
    style: {
      presetId: 'warm-orange',
      background: '#f5f0eb',
      ownerTextColor: '#ffffff',
      ownerBgColor: '#FF8C42',
      otherTextColor: '#333333',
      otherBgColor: '#ffffff',
      dateTextColor: '#aa8866',
      avatarRadius: 6,
      bubbleRadius: 6,
    },
  },
  {
    id: 'rose-pink',
    label: '玫红',
    thumb: { owner: '#E91E8C', other: '#ffffff', bg: '#faf0f5' },
    style: {
      presetId: 'rose-pink',
      background: '#faf0f5',
      ownerTextColor: '#ffffff',
      ownerBgColor: '#E91E8C',
      otherTextColor: '#333333',
      otherBgColor: '#ffffff',
      dateTextColor: '#b08090',
      avatarRadius: 4,
      bubbleRadius: 4,
    },
  },
  {
    id: 'purple',
    label: '紫色',
    thumb: { owner: '#7C4DFF', other: '#ffffff', bg: '#f3f0fa' },
    style: {
      presetId: 'purple',
      background: '#f3f0fa',
      ownerTextColor: '#ffffff',
      ownerBgColor: '#7C4DFF',
      otherTextColor: '#333333',
      otherBgColor: '#ffffff',
      dateTextColor: '#9988aa',
      avatarRadius: 4,
      bubbleRadius: 4,
    },
  },
  {
    id: 'dark',
    label: '深色',
    thumb: { owner: '#1261FF', other: '#3a3a3a', bg: '#1a1a1a' },
    style: {
      presetId: 'dark',
      background: '#1a1a1a',
      ownerTextColor: '#ffffff',
      ownerBgColor: '#1261FF',
      otherTextColor: '#eeeeee',
      otherBgColor: '#3a3a3a',
      dateTextColor: '#888888',
      avatarRadius: 4,
      bubbleRadius: 4,
    },
  },
  {
    id: 'mono',
    label: '黑白',
    thumb: { owner: '#222222', other: '#ffffff', bg: '#f0f0f0' },
    style: {
      presetId: 'mono',
      background: '#f0f0f0',
      ownerTextColor: '#ffffff',
      ownerBgColor: '#222222',
      otherTextColor: '#111111',
      otherBgColor: '#ffffff',
      dateTextColor: '#888888',
      avatarRadius: 0,
      bubbleRadius: 2,
    },
  },
]

export function getChatStylePreset(id) {
  return CHAT_STYLE_PRESETS.find((p) => p.id === id) || null
}
